In [ ]:
import pandas as pd
import requests

"""
https://youtu.be/roTZJaxjnJc?list=PLKnIA16_Rmvbr7zKYQuBfsVkjoLcJgxHH
"""

In [ ]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1')

"""
Ye line TMDB API se data fetch kar rahi hai.
response =
API ka response response variable me store hoga.

requests.get(...)
Ye API URL par GET request bhejta hai.
GET request ka matlab: server se data maangna.

URL breakdown:
https://api.themoviedb.org/3/movie/top_rated
Ye endpoint top rated movies ka data deta hai.

api_key=...
API key hai. API ko access karne ke liye key chahiye hoti hai.

language=en-US
Movies ka data English/US language me chahiye.

page=1
Page number 1 ka data chahiye.

API ek baar me limited movies deti hai, isliye pages use hote hain.
"""

ConnectTimeout: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1 (Caused by ConnectTimeoutError(<HTTPSConnection(host='api.themoviedb.org', port=443) at 0x121d75da9f0>, 'Connection to api.themoviedb.org timed out. (connect timeout=None)'))

In [ ]:
temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [ ]:
df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,18.433,8.7,2763
1,724089,Gabriel's Inferno Part II,Professor Gabriel Emerson finally learns the t...,2020-07-31,8.439,8.7,1223
2,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,1994-09-23,65.570,8.7,18637
3,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,63.277,8.7,14052
4,761053,Gabriel's Inferno Part III,The final part of the film adaption of the ero...,2020-11-19,26.691,8.7,773

In [ ]:
df = pd.DataFrame()

In [ ]:
df

Empty DataFrame
Columns: []
Index: []

In [ ]:
for i in range(1,429):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(i))
    temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    df = df.append(temp_df,ignore_index=True)

    """
Ye main part hai.
Yahaan multiple API pages se movies ka data fetch kiya ja raha hai.

for i in range(1,429):
Loop page numbers ke liye chal raha hai.
range(1,429) ka matlab:
Start: 1
End: 429 se pehle tak
Actual values:
1, 2, 3, ..., 428
Matlab total 428 pages fetch honge.

response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(i))
Har loop me API request bheji ja rahi hai.

Important part:
page={}.format(i)
Yahaan page number dynamic ban raha hai.
Agar i = 1, URL me:
page=1
Agar i = 2, URL me:
page=2
Agar i = 428, URL me:
page=428
Matlab har baar different page ka data fetch hoga.

temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
Har page ke response ko DataFrame me convert kiya ja raha hai.
Sirf selected columns rakhe ja rahe hain.
temp_df me ek page ka data hoga.
Usually TMDB ek page me 20 movies deta hai.

df = df.append(temp_df,ignore_index=True)
Yahaan temp_df ko final df ke andar add kiya ja raha hai.

df.append(temp_df)
Purane df ke neeche temp_df ki rows add karta hai.

ignore_index=True
Index ko reset karta hai.
Agar ye na lagao, to har page ka index 0 se start ho sakta hai.

ignore_index=True se final index continuous hota hai:
0, 1, 2, 3, ...

Important note:
New pandas versions me .append() deprecated/removed ho chuka hai.
Modern code me better hai:
pd.concat()
"""

In [ ]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,18.433,8.7,2763
1,724089,Gabriel's Inferno Part II,Professor Gabriel Emerson finally learns the t...,2020-07-31,8.439,8.7,1223
2,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,1994-09-23,65.570,8.7,18637
3,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,63.277,8.7,14052
4,761053,Gabriel's Inferno Part III,The final part of the film adaption of the ero...,2020-11-19,26.691,8.7,773
...,...,...,...,...,...,...,...
8546,13805,Disaster Movie,"The filmmaking team behind the hits ""Scary Mov...",2008-08-29,14.630,3.2,714
8547,5491,Battlefield Earth,"In the year 3000, man is no match for the Psyc...",2000-05-12,10.647,3.0,543
8548,14164,Dragonball Evolution,The young warrior Son Goku sets out on a quest...,2009-03-12,32.244,2.8,1447
8549,11059,House of the Dead,"Set on an island off the coast, a techno rave ...",2003-04-11,14.502,2.8,238
8550,40016,Birdemic: Shock and Terror,A platoon of eagles and vultures attacks the r...,2010-02-27,9.824,2.2,215

In [ ]:
df.shape
"""
Ye DataFrame ka size batata hai.

Output format hota hai:
(rows, columns)
Example:
(8560, 7)

Matlab:
8560 rows
7 columns

Agar har page me 20 movies hain aur 428 pages hain:
428 * 20 = 8560
To expected rows around 8560 ho sakti hain.
"""

(8551, 7)

In [ ]:
df.to_csv('movies.csv')
"""
Final data ko CSV file me save karo.
"""